version: '3'
services:
  streamlit:
    build:
      context: .
      dockerfile: streamlit/Dockerfile
    ports:
      - "80:8501"
  
  flask:
    build:
      context: .
      dockerfile: flask/Dockerfile
    ports:
      - "8502:8502"
